### ISSUE TITLE
view reduced to a size 1 array

### ISSUE THREAD

**Issue by chanokin** [genn-team/ml_genn#20]
I was getting low performance in the GeNN version of the simple CNN example and I think it may be due to using a batch size of 1 and the following lines of the evaluate method 
https://github.com/genn-team/ml_genn/blob/a88cf1af6bddf95e4e31c38af0d80cb12ea25e3e/ml_genn/model.py#L212-L214

I just changed it to 
```python
output_view = nrn.vars['nSpk'].view.reshape(batch_n, -1)
```
and it seems to be working ok now.

**Comment by jamesturner246** [comment]
Thanks Gary. Sorry I missed you earlier. I'll make a fix. I have a funny feeling that some corner case will mess things up if we change the size of the pygenn views, but maybe not. Will see..
