### ISSUE TITLE
Results with example vgg16.py

### ISSUE THREAD

**Issue by kroll-software** [genn-team/ml_genn#22]
I ran the vgg16.py example successfully. A few hours later I got 10% accuracy for the SNN using the CIFAR-10 dataset, which is pretty much the exact random distribution result for 10 classes, isn't it?

Is that correct or did something went wrong?

**Comment by jamesturner246** [comment]
Likely fixed in #21. See if the problem still occurs using the `fix-size-one-batch` branch.

**Comment by kroll-software** [comment]
the fix in #21 worked and I get an accuracy of 60.14,
still not the very best compared to the Tensorflow result, but much better now.

Thank you for quick answers.
