### ISSUE TITLE
Activation layers

### ISSUE THREAD

**Issue by neworderofjamie** [genn-team/ml_genn#29]
As well as specifying the activation via the ``activation="xxx"`` kwarg of layer objects, you can also specify it with specific activation layers. See https://keras.io/api/layers/activations/

**Comment by jamesturner246** [comment]
This would need to be limited to after non-activation layers, such as pooling layers. It could be done in a manner similar to `AvePooling2DDense`, but with identity Dense weights. So MLG might convert a TF model pooling layer -> activation layer into an `AvePooling2D` layer, which must have an activation function (taken from the activation layer).

The identity Dense weights would not need to be stored - it could all be done in procedural connectivity.

**Comment by neworderofjamie** [comment]
To be clear, am I right in thinking that it's an alternative way of specifying the activation functions that follow layers rather than a way of letting you have multiple back-to-back activation functions (I don't really know what that would do)? If so, I totally agree it should be handled like ``AvePooling2DDense`` style stuff.

**Comment by jamesturner246** [comment]
The former, I'm sure. Back to back activation seems pretty weird and pointless!
