### ISSUE TITLE
GlobalAveragePooling2D  layers

### ISSUE THREAD

**Issue by neworderofjamie** [genn-team/ml_genn#30]
These can be implemented using average pooling layers but the pool is the entire previous layer (so they pool a whole channel into one value). See https://keras.io/api/layers/pooling_layers/global_average_pooling2d/ and https://machinelearningmastery.com/pooling-layers-for-convolutional-neural-networks/

**Comment by jamesturner246** [comment]
This is a trivial one. I'll tweak the conversion code to handle globalaveragepooling layers. I'm not sure it's worth adding a new ml_genn layer, but I could do if it's really wanted.

**Comment by neworderofjamie** [comment]
I think tweaking the conversation code is the way to go

**Comment by jamesturner246** [comment]
Done in #31
