### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by neworderofjamie** [genn-team/ml_genn#58]
Not 100% sure where this should be integrated:
- Some things e.g. random shift or time dilation _could_ be added to ``SpikeSourceInput``
- It would be nice to support tonic's existing augmentation library

**Comment by tnowotny** [comment]
A couple of thoughts, so the idea here is to not add anything to mlgenn, meaning that the metrics returned for the single epoch training would be for a single epoch and users would collect themselves (if desired) like so:
``` 
 metrics, _  = compiled_net.train({input: spikes},
                                     {output: labels},
                                     start_epoch=e, num_epochs=1, shuffle=True,
                                     callbacks=callbacks)
all_matrics.append(metrics)
```
regarding the ```DiskCachedDataset```, I agree, normal looping through tonic datasets can be very slow and formatting e.g. SSC into spikes doing this takes some 15 min.

**Comment by neworderofjamie** [comment]
The metrics were indeed one of the "few rough edges" I was alluding to! I might add some functionality for combining lists of metrics or something.

**Comment by tnowotny** [comment]
I am not sure that anything needs to be provided - maybe it is enough to be clear about it and provide an example?

**Comment by neworderofjamie** [comment]
Good point, metrics get reset every epoch anyway
